#!/bin/bash
set -x
download_url: http://download.oracle.com/otn-pub/java/jdk/8u5-b13/jdk-8u5-linux-x64.tar.gz
download_folder=/opt
download_url=http://download.oracle.com/otn-pub/java/jdk/8u191-b12/2787e4a523244c269598db4e85c51e0c/jdk-8u191-linux-x64.tar.gz

java_archieve=jdk-8u191-linux-x64.tar.gz

java_package=${download_folder}/${java_archieve}
wget -q  -O /opt/jdk-8u191-linux-x64.tar.gz --no-check-certificate --no-cookies --header 'Cookie: oraclelicense=accept-securebackup-cookie' "${download_url}"

#Unpack archive
tar -zxf ${java_package} -C ${download_folder}

java_folder=jdk1.8.0_191


sudo update-alternatives --install "/usr/bin/java" "java" "${download_folder}/${java_folder}/bin/java" 1
sudo update-alternatives --install "/usr/bin/javac" "javac" "${download_folder}/${java_folder}/bin/javac" 1
sudo update-alternatives --install "/usr/bin/javaws" "javaws" "${download_folder}/${java_folder}/bin/javaws" 1


echo "export JAVA_HOME=${download_folder}/${java_folder}" >>/etc/profile.d/java8.sh
echo "export PATH=$PATH:$JAVA_HOME/bin">>/etc/profile.d/java8.sh
